name: CI/CD Pipeline for Frontend Deployment

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  deploy-to-aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AKS_CLUSTER }}

      - name: Update Deployment to Pull `ram-frontend` from Docker Hub
        run: |
          kubectl set image deployment/frontend-demo frontend-demo=venkat345/ram-frontend:latest --namespace=default

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f manifests/deployment.yaml
          kubectl apply -f manifests/service.yaml
