apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo-deployment
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-demo
  template:
    metadata:
      labels:
        app: frontend-demo
    spec:
      containers:
        - name: frontend-demo-container
          image: venkat345/ram-frontend:latest  # Updated with "demo" in the name
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service.default.svc.cluster.local"
