apiVersion: v1
kind: Service
metadata:
  name: frontend-demo-service
  namespace: frontend
spec:
  selector:
    app: frontend-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
